{{- if .Values.spire.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-spire
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-server
type: Opaque
data:
  database-password: {{ .Values.spire.database.password | b64enc | quote }}
{{- end }}
