{{- if and (not .Values.valkey.enabled) .Values.externalValkey.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-external-valkey
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
type: Opaque
data:
  valkey-password: {{ .Values.externalValkey.password | b64enc | quote }}
{{- end }}
